### ISSUE TITLE
Could you give a specific example about "$ ./prep_all_data.sh <HUMAN_FRIENDLY_DATASET_NAME> path/to/data/file.json"

### ISSUE THREAD

**Issue by ZhichaoOuyang** [noveens/reviews4rec#1]
I don’t understand how to fill in the last two parameters. 
Can you give a specific example?
Thanks.

**Comment by noveens** [comment]
Sure, here is an example command:
```bash
./prep_all_data.sh clothing ./reviews_Clothing_Shoes_and_Jewelry_5.json
```

With this command, my intent is to preprocess the 5-core version of Amazon's clothing, shoes, and jewelry dataset downloaded from [Prof. McAuley's webpage](http://jmcauley.ucsd.edu/data/amazon/links.html). The script will then create the data files under the directory `./data/clothing/` since we provided the human-friendly name as `clothing`.

Does that help? If not, please feel free to comment with any further questions you have.

Cheers,
Noveen

**Comment by ZhichaoOuyang** [comment]
Thank you very much for solving my problem!
